### ISSUE TITLE
Multiple milestones option issue

### ISSUE THREAD

**Issue by Subhash-Karri** [questbook/grants-frontend#106]
Created 'Freetokens DAO' and created a grant with 'mulitple milestones'

Issue 1: I don't see an option of updating the different milestones.
Issue 2: While I selected multiple milestones option, it still shows on the link as 'single milestone'

**Comment by roohchillsharma** [comment]
https://www.loom.com/share/cecc8856aef24b12b8936529389241c4

**Comment by AlwaysHungrie** [comment]
Fixed
![image](https://user-images.githubusercontent.com/19796784/156977671-9119ba63-6329-462c-bcc1-097c8012b7d9.png)
