### ISSUE TITLE
No check of links for project links in apply for a grant form

### ISSUE THREAD

**Issue by rajkaria** [questbook/grants-frontend#107]
<img width="475" alt="Screenshot 2022-03-04 at 12 54 07" src="https://user-images.githubusercontent.com/29420323/156718332-15c00094-1db3-4fd6-bce2-082031833756.png">

**Comment by rajkaria** [comment]
I was able to add normal text in "project link 1"

**Comment by AlwaysHungrie** [comment]
Duplicate of #96
