### ISSUE TITLE
More information on error popup

### ISSUE THREAD

**Issue by madhavanmalolan** [questbook/grants-frontend#109]
This error was not intuitive that it was because i didn't have the funds
![image](https://user-images.githubusercontent.com/2111253/156719054-a0d633e5-4d7f-4a64-9274-63b9e1d3c80a.png)

**Comment by krati-creatoros** [comment]
Another scenario : manually "Reject" in metamask while creating a GrantsDAO. The error message is still the same "Transaction Failed" ; ideally it should be "Please accept the metamask request"

**Comment by richikchanda1999** [comment]
> Another scenario : manually "Reject" in metamask while creating a GrantsDAO. The error message is still the same "Transaction Failed" ; ideally it should be "Please accept the metamask request"

<img width="1434" alt="Screenshot 2022-03-08 at 1 20 15 PM" src="https://user-images.githubusercontent.com/27001160/157191137-50de27c4-8ee0-48e6-89c5-4ed30144797f.png">

**Comment by richikchanda1999** [comment]
<img width="1439" alt="Screenshot 2022-03-08 at 1 19 14 PM" src="https://user-images.githubusercontent.com/27001160/157191581-b76d5bef-3a27-4c9f-a932-72b4858df999.png">
 @madhavanmalolan Added some more info
