### ISSUE TITLE
create grants DAO -> Fix image upload flow

### ISSUE THREAD

**Issue by krati-creatoros** [questbook/grants-frontend#111]
**To Reproduce**
Create a grants DAO. Upload a logo image.
1. Firstly a loader should be shown 
2. When image upload fails, the error shown is "Transaction Failed"
<img width="779" alt="Screenshot 2022-03-04 at 12 58 02 PM" src="https://user-images.githubusercontent.com/88843644/156719475-786bbeac-acd4-40cc-b15b-adc02bb87e0d.png">

**Comment by gyan0890** [comment]
Error message missing while creating a DAO: Image is mandatory. 
If I don’t upload the image, it doesn’t move forward.

**Comment by richikchanda1999** [comment]
@ankitnairr Need to know how to display mandatory and optional fields

**Comment by roohchillsharma** [comment]
@ankitnairr

**Comment by roohchillsharma** [comment]
1. One static image as a placeholder @ankitnairr 
2. Image uploading will be optional
