### ISSUE TITLE
Create Grants DAO with a really heavy image logo

### ISSUE THREAD

**Issue by krati-creatoros** [questbook/grants-frontend#113]
Ideally we should ask them to upload logo within a given size limit

**Comment by AlwaysHungrie** [comment]
Not strongly enforceable as we are using ipfs
best we can do is deter users from uploading large files from the UI

**Comment by richikchanda1999** [comment]
<img width="1424" alt="Screenshot 2022-03-11 at 11 49 13 AM" src="https://user-images.githubusercontent.com/27001160/157813652-42c6f976-3e46-4759-b8cc-493013e0406b.png">
