### ISSUE TITLE
Discover Grants - filter for chains

### ISSUE THREAD

**Issue by gyan0890** [questbook/grants-frontend#115]
**Is your feature request related to a problem? Please describe.**
Under Discover Grants - can we add a filter for chains or add the chain symbol next to the grant name?

**Describe the solution you'd like**
A symbol next to the name of the grant or a filter on top to filter grants by chains.

**Additional context**
Unable to find grants for specific chains that I am looking for.

**Comment by AlwaysHungrie** [comment]
Closing this for now, will reopen in the future
