### ISSUE TITLE
grant creation message

### ISSUE THREAD

**Issue by krati-creatoros** [questbook/grants-frontend#116]
1. we should add some message for user to hint about avg  grant creation; just for a better user experience.
<img width="834" alt="Screenshot 2022-03-04 at 1 16 18 PM" src="https://user-images.githubusercontent.com/88843644/156721292-a2481b45-f0d5-4161-b01f-47dee541643c.png">

2. On same page we should also say "You can view your created grant under <this section> once its ready"

**Comment by madhavanmalolan** [comment]
Duplicate : 
https://github.com/questbook/grants-frontend/issues/92

**Comment by roohchillsharma** [comment]
@AlwaysHungrie : Can you assign the priority and owner of this issue?

**Comment by AlwaysHungrie** [comment]
this will be resolved once optimistic loading is implemented. Don't see a point in fixing these screens because they changes will be shortlived
