### ISSUE TITLE
Apply grant: Technical field displayed

### ISSUE THREAD

**Issue by Subhash-Karri** [questbook/grants-frontend#117]
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/83459897/156721700-5d8c397c-daf9-4cd8-abb8-e69e2ed72eea.png">
As an applicant if I apply for a grant, on the right side I see all the requisite fields. Fields like 'IsMultipleMilestones' are redundant and also the field names should be descriptive

**Comment by AlwaysHungrie** [comment]
![image](https://user-images.githubusercontent.com/19796784/156980342-6486aaea-58da-48b3-b72c-18d38a815bec.png)
