### ISSUE TITLE
Milestones amounts check

### ISSUE THREAD

**Issue by Subhash-Karri** [questbook/grants-frontend#121]
<img width="618" alt="image" src="https://user-images.githubusercontent.com/83459897/156726117-e461bdc3-51f1-4a22-bbd6-b11ed69253f7.png">

Milestones amounts should add up to the 'Fund ask' but there is no check if it doesn't. This will create confusion during grants budgeting and payments. 

If the milestone total amount is more than the fund ask, the grants team would have budgeted only for 'Fund ask' and would have overshot their budget.

If the milestones total amount is less than the fund ask, the applicant would be paid less than the fund ask and again will have to ask for the money and get a separate payment initiated outside the tool.

Both these scenarios are an operational hassle for the grants team.

**Comment by roohchillsharma** [comment]
@AlwaysHungrie : Can you assign the priority and owner of this issue?

**Comment by AlwaysHungrie** [comment]
@ankitnairr depending on what you decide there will be smart contract changes required.
Need to have clear thoughts regarding this

**Comment by roohchillsharma** [comment]
Sum of milestone reward amount should be equal to the final ask amount on the application page, but the Grants DAO should be able to send any amount of funds to the applicant.

**Comment by abhilashi** [comment]
we shouldn't fix this
