### ISSUE TITLE
Grant entry missing from Discover grants

### ISSUE THREAD

**Issue by Subhash-Karri** [questbook/grants-frontend#125]
Under 'FreeTokens DAO', i have listed 'Month 1 Airdrop' grant application and even submitted an application for the same.

However, I am not finding it now in Discover Grants.

https://www.loom.com/share/368a7909703840f7b80d08546fc33b74

**Comment by AlwaysHungrie** [comment]
fixed 
![image](https://user-images.githubusercontent.com/19796784/156983769-19e9167c-dabe-425a-abac-ed8117444408.png)
