### ISSUE TITLE
Unable to create grants with Gnosis Multi - Sig Wallet

### ISSUE THREAD

**Issue by roohchillsharma** [questbook/grants-frontend#126]
1. Connected Gnosis with Wallet connect (2/2) mult- sig
2. Tried creating the grant through Questbook, but it failed 
3. The transactions did not get queued on Gnosis

https://www.loom.com/share/3040fc6720ae4451a77c98757f8c1729

**Comment by roohchillsharma** [comment]
@roohchillsharma to test this again

**Comment by AlwaysHungrie** [comment]
Stopping support for gnosis safe for the moment. Let's revisit this after p1
