### ISSUE TITLE
At times, submit application CTA does not work 

### ISSUE THREAD

**Issue by roohchillsharma** [questbook/grants-frontend#128]
https://www.loom.com/share/c33cec00d4454c1983ddc1c020412a27

**Comment by abhilashi** [comment]
@AlwaysHungrie @SahilVasava is this a rinkeby issue?

**Comment by SahilVasava** [comment]
@abhilashi It's because of incorrect email in the form. But agree, this needs better handling of incorrect data format or missing issue.

**Comment by AlwaysHungrie** [comment]
Duplicate of #98
