### ISSUE TITLE
Bug in formatting token amount values in apply for grant form

### ISSUE THREAD

**Issue by SahilVasava** [questbook/grants-frontend#130]
**Description**
The token amount values changes automatically to negative number. Some sort of formatting bug.

**To Reproduce**
1. Go to [apply for grant](http://localhost:3000/explore_grants/apply/?account=true&grantId=0xad413d2ff191f044d5b727703b6c4ba20aac79b6&chainId=4)
2. Enter all other details
3. Enter `1` in expected milestone reward
4. Move away to fill other details
5. It changes to `-1`

**Expected behavior**
It should be exactly as the user entered.

**Screenshots**
<img width="812" alt="image" src="https://user-images.githubusercontent.com/24778390/156984424-5e06aa26-c841-4216-a562-2ce3002d8f5a.png">

**Comment by AlwaysHungrie** [comment]
this is happening because on scrolling after entering input, the focus is not shifting and browser thinks you are trying to change the value using scroll
