### ISSUE TITLE
Harmony Grant created but 'Learn more' points to etherscan

### ISSUE THREAD

**Issue by Subhash-Karri** [questbook/grants-frontend#131]
I don't have the screenshot but I created a grant in my Grants DAO and it popped up a message:
'Last activity under process and will take a few mins. Learn More'. 

Learn More link points to Etherscan but should instead point to the respective explorer of the protocol.

**Comment by AlwaysHungrie** [comment]
@AlwaysHungrie need to move on to dynamic block explorer links
