### ISSUE TITLE
Polygon name appear in generic application

### ISSUE THREAD

**Issue by Subhash-Karri** [questbook/grants-frontend#133]
<img width="592" alt="image" src="https://user-images.githubusercontent.com/83459897/156994629-7b033350-1232-450f-9e2c-8c0c07864bdf.png">

This is a harmony application and people would not like to see 'Polygon' name in the suggestion. The suggestions have to be generic across the board. cc: Ankit Nair

**Comment by AlwaysHungrie** [comment]
Duplicate of #99
