### ISSUE TITLE
Metmask Harmony S0 shows polygon icon

### ISSUE THREAD

**Issue by Subhash-Karri** [questbook/grants-frontend#140]
<img width="243" alt="image" src="https://user-images.githubusercontent.com/83459897/157075409-37f51828-cdae-4a1a-8b43-66f28b72db48.png">

**Comment by AlwaysHungrie** [comment]
![image](https://user-images.githubusercontent.com/19796784/157083412-74c8efea-0885-4a0f-aca8-ba90f9792edc.png)
