### ISSUE TITLE
Unable to view "My Applications tab" after successfully submitting the application. 

### ISSUE THREAD

**Issue by roohchillsharma** [questbook/grants-frontend#153]
I submitted the application successfully, but was unable to view the 'My applications' tab on the Home Page. 

<img width="1791" alt="Screenshot 2022-03-09 at 8 27 15 PM" src="https://user-images.githubusercontent.com/83450876/157467867-3dbcd539-a441-4f50-92c8-11b1befa1e3f.png">

**Comment by richikchanda1999** [comment]
<img width="1427" alt="Screenshot 2022-03-11 at 11 38 19 AM" src="https://user-images.githubusercontent.com/27001160/157812138-70154962-22ff-44d1-8db6-c857fd1441a6.png">
