### ISSUE TITLE
Text not linkified

### ISSUE THREAD

**Issue by madhavanmalolan** [questbook/grants-frontend#174]
![image](https://user-images.githubusercontent.com/2111253/157886763-13eaea11-3b96-4119-a881-43dcc3d53566.png)

**Comment by richikchanda1999** [comment]
<img width="690" alt="Screenshot 2022-03-14 at 1 53 34 PM" src="https://user-images.githubusercontent.com/27001160/158132947-7a929e41-5011-4efa-9ca4-eeafb8d71079.png">
