### ISSUE TITLE
Personal Information Encryption - Learn more link is missing

### ISSUE THREAD

**Issue by ankitnairr** [questbook/grants-frontend#205]
**Describe the bug**
Why is this required hyperlink - create a grant is missing.
**To Reproduce**
1. Go to Create a Grant
2. Applicant Details
3. Switch on "Hide Applicant Personal Data" toggle to ON.
4. Click on "Why is this required?" 
5. See error

**Expected behavior**
Notion doc FAQ explaining the context of the feature.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 99.0.4844.51

**Additional context**

**Comment by SahilVasava** [comment]
@ankitnairr Please provide a notion doc link. I'll put it there.

**Comment by SahilVasava** [comment]
Added link to an empty doc. 
[TODO]: Add content in doc. [Document](https://www.notion.so/questbook/Why-is-public-key-required-e3fa53f34a5240d185d3d34744bb33f4)
