### ISSUE TITLE
Request Public Key in onboarding journey - Shown to Grants DAO creator

### ISSUE THREAD

**Issue by ankitnairr** [questbook/grants-frontend#210]
**Describe the bug**
If the Grants DAO has no grants, the grants tab side panel has a section which instructs the user to provide to his public key.

**To Reproduce**
1. Create a Grants DAO
2. Click on "I'll do it later" link below Create Grant
3. See the right pane.

**Expected behavior**
Remove the section which instructs the user to provide his public key.

**Screenshots**
[If applicable, add screenshots to help explain your problem.
](https://prnt.sc/kycUzExkujJy)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 99

**Comment by SahilVasava** [comment]
@ankitnairr 
It's good thing if they provide the public key beforehand. If they provide the public key while creating a grant the subgraph takes time to index the public key which is needed while an applicant is applying. If they provide beforehand, it gives subgraph some time to index so no dropped transactions. 
What I can do though is change the order, keep the `Create your first grant` element first and this one second.
