### ISSUE TITLE
Tooltip not useful at all

### ISSUE THREAD

**Issue by madhavanmalolan** [questbook/grants-frontend#77]
For which persona is this tool tip relevant?

![image](https://user-images.githubusercontent.com/2111253/156615620-7d8efd88-44ee-4da4-b55e-b2741cef8624.png)

**Comment by roohchillsharma** [comment]
@ankitnairr

**Comment by ankitnairr** [comment]
Removing this. Was intended for someone who is new to web3. Our target audience definitely would know about and also own a wallet. @AlwaysHungrie @richikchanda1999 Please note.
