### ISSUE TITLE
Display text placeholders not replaced

### ISSUE THREAD

**Issue by madhavanmalolan** [questbook/grants-frontend#79]
![image](https://user-images.githubusercontent.com/2111253/156617415-0142c45b-dd71-4f00-bbca-aa6896d44a0d.png)

**Comment by AlwaysHungrie** [comment]
![image](https://user-images.githubusercontent.com/19796784/156971213-82932018-be40-4146-b9c0-6e84bcc5b2cd.png)


@richikchanda1999  this is fixed but still getting invalid field in few grants.
Need to check why/where is this field getting added in 3 places: getting started, edit and create grants

**Comment by AlwaysHungrie** [comment]
issue is fixed

![image](https://user-images.githubusercontent.com/19796784/157004045-a6bd5a28-3222-4c9c-94ab-dca429592bc5.png)
