### ISSUE TITLE
Inconsistent copy

### ISSUE THREAD

**Issue by madhavanmalolan** [questbook/grants-frontend#80]
The expectation on the grant creator and applicant not consistent for the "Funding Breakdown" Field
![image](https://user-images.githubusercontent.com/2111253/156617856-38d46423-c8c9-41eb-8dd1-9bc42eb58ccf.png)

![image](https://user-images.githubusercontent.com/2111253/156617939-cddbdfa9-9dbf-4e07-81de-a67206e40d27.png)

**Comment by roohchillsharma** [comment]
@ankitnairr

**Comment by richikchanda1999** [comment]
<img width="381" alt="Screenshot 2022-03-11 at 11 57 53 AM" src="https://user-images.githubusercontent.com/27001160/157814485-d1ac4529-e46d-4723-a6f8-14d59ed0462b.png">
<img width="594" alt="Screenshot 2022-03-11 at 11 58 17 AM" src="https://user-images.githubusercontent.com/27001160/157814492-7a230f2e-cc27-4a1e-8142-f5c5d7ba36cd.png">
<img width="629" alt="Screenshot 2022-03-11 at 11 58 30 AM" src="https://user-images.githubusercontent.com/27001160/157814499-4a34c214-2cbe-4242-9b9a-3aa40b22291d.png">
