### ISSUE TITLE
Extraneous Scrollbars 

### ISSUE THREAD

**Issue by madhavanmalolan** [questbook/grants-frontend#82]
![image](https://user-images.githubusercontent.com/2111253/156618568-7ee2dac8-7ce2-4e18-a084-bdbefef5de5e.png)

**Comment by AlwaysHungrie** [comment]
Need to test this on
1. Firefox
2. Brave
3. Safari 

before merging

**Comment by AlwaysHungrie** [comment]
@madhavanmalolan I have tried this on 
Brave, Firefox and Chrome on my machine.

Is this is a windows specific issue. I am hardcoding not to show the horizontal scrollbar. 

Please reopen if this doesn't fix it
