### ISSUE TITLE
Wrong message when wallet is locked

### ISSUE THREAD

**Issue by madhavanmalolan** [questbook/grants-frontend#86]
I was on the correct network, but my wallet had gotten locked. 

![image](https://user-images.githubusercontent.com/2111253/156712848-81cee4c9-9cc0-42d5-a14f-955c29bff068.png)

**Comment by AlwaysHungrie** [comment]
@madhavanmalolan can you provide steps to reproduce? Either its a problem with metamask i.e. it didn't show the popup/timed out or you were applying to a grant which was listed on Rinkeby and not harmony

**Comment by AlwaysHungrie** [comment]
![image](https://user-images.githubusercontent.com/19796784/157679544-69f3c915-3289-4db7-be05-cc8f8f1e40d8.png)
