### ISSUE TITLE
Terms of Service should be a link; not just text

### ISSUE THREAD

**Issue by krati-creatoros** [questbook/grants-frontend#87]
**Describe the bug**
On connect wallet screen, footer at bottom should have link to Terms of Service.

**Screenshots**
<img width="633" alt="Screenshot 2022-03-04 at 12 09 05 PM" src="https://user-images.githubusercontent.com/88843644/156712919-e618fe30-97d9-463d-80e5-727cc6adea8b.png">

**Comment by AlwaysHungrie** [comment]
moved to https://github.com/questbook/grants-frontend/issues/89
