### ISSUE TITLE
"Connect your wallet " opens random Notion doc

### ISSUE THREAD

**Issue by krati-creatoros** [questbook/grants-frontend#88]
**Describe the bug**
"Connect your wallet" on getting started page should either behave same way as "Connect wallet" button at top or it should open a link to explain how to connect wallet. Currently it opens random FAQ notion doc.

**Screenshots**
<img width="990" alt="Screenshot 2022-03-04 at 12 14 30 PM" src="https://user-images.githubusercontent.com/88843644/156713444-3075c70d-210e-48ac-ba84-0476c3dc2e06.png">

**Comment by AlwaysHungrie** [comment]
Fixed.
Connect your wallet redirects to questbook.app/connect_wallet
