### ISSUE TITLE
Have to enter no of team member as input even after entering their names

### ISSUE THREAD

**Issue by sourav-bz** [questbook/grants-frontend#90]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

![Screen Shot 2022-03-04 at 12 23 42 PM](https://user-images.githubusercontent.com/22414946/156714607-20171799-8ced-4ded-b822-e4ad784ff004.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AlwaysHungrie** [comment]
need to change number of team members to a dropdown
