### ISSUE TITLE
Wrong network message is not showing up

### ISSUE THREAD

**Issue by Subhash-Karri** [questbook/grants-frontend#91]
Tried selecting the Harmony S0 on beta.questbook.app but my metamask was still on 'Mainnet network'. I could see the 'Unsupported network' on the wallet on the top in small letters but there was no error popup. I feel this should be fixed.

**Comment by Subhash-Karri** [comment]
Infact, even when I select Harmony S0 on my metamask, it still show 'unsupported network'.

https://www.loom.com/share/b3103e6ce4ee404b930785ffd6fbc37e

**Comment by AlwaysHungrie** [comment]
@ankitnairr need more **friendly** ux for users navigating across chains
