### ISSUE TITLE
Using harmony test net but account description on top right says "unsupported network"

### ISSUE THREAD

**Issue by krati-creatoros** [questbook/grants-frontend#93]
**Describe the bug**
Using harmony test net but account description on top right says "unsupported network"

**Screenshot**
<img width="591" alt="Screenshot 2022-03-04 at 12 29 34 PM" src="https://user-images.githubusercontent.com/88843644/156715173-0541dfaa-bcdc-4ebf-872c-a5343b668ba8.png">

**Comment by AlwaysHungrie** [comment]
Duplicate of #91
