### ISSUE TITLE
Newly created grant 5-6 scrolls below the fold 

### ISSUE THREAD

**Issue by madhavanmalolan** [questbook/grants-frontend#94]
I created this DAO on Harmony. Looks like all the harmony grants are getting appended after the rinkeby ones.
Some sorting required here

![image](https://user-images.githubusercontent.com/2111253/156715332-d8e2b612-b141-47e1-96a7-deb82782dbbb.png)

**Comment by AlwaysHungrie** [comment]
Fixed
All grants across all chains are sorted in reverse order of the date created
