### ISSUE TITLE
Copy Issues

### ISSUE THREAD

**Issue by madhavanmalolan** [questbook/grants-frontend#99]
A thread for all copy issues

**Comment by madhavanmalolan** [comment]
The help text should be a better one
maybe something like "https://t.me/questbook"
![image](https://user-images.githubusercontent.com/2111253/156717064-23796cfc-7e20-46bc-9533-8e031c838593.png)

**Comment by roohchillsharma** [comment]
The application should show closed instead of complete when the member of a grants DAO marks the application as closed. https://clb.sh/f526cb

**Comment by roohchillsharma** [comment]
"Verified Smart Contract CTA" does not work. 

https://www.collabshot.com/show/d33ecd

**Comment by AlwaysHungrie** [comment]
https://github.com/questbook/grants-frontend/issues/118

**Comment by roohchillsharma** [comment]
@AlwaysHungrie : Can you assign the priority and owner of this issue?

**Comment by AlwaysHungrie** [comment]
https://github.com/questbook/grants-frontend/issues/133
